/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import bo.MovimentacaoBO;
import bo.ProdutoBO;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Movimentacao;

/**
 *
 * @author User
 */
public class TelaMovimentacao extends javax.swing.JInternalFrame {

    private MovimentacaoBO objMovimentacao = new MovimentacaoBO();
    private JDesktopPane desktopPane;
    private ProdutoBO objProduto = new ProdutoBO();

    public TelaMovimentacao(JDesktopPane desktopPane) {
        initComponents();

        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        setBorder(null);
        this.desktopPane = desktopPane;

        carregarProdutos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtDataMovimentacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtQntdMovimentada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxTipodeMovimentacao = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        BtnGerenciar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        comboBoxProdutos = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(879, 571));

        jLabel2.setText("Nome do Produto: ");

        jLabel3.setText("Data:");

        jLabel4.setText("Quantidade Movimentada: ");

        jLabel6.setText("Tipo da Movimentação:");

        comboBoxTipodeMovimentacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Saida" }));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        BtnGerenciar.setText("Gerenciar");
        BtnGerenciar.addActionListener(this::BtnGerenciarActionPerformed);

        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);

        comboBoxProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnGerenciar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(TxtQntdMovimentada, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxTipodeMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboBoxProdutos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtDataMovimentacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDataMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtQntdMovimentada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxTipodeMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadastrar)
                            .addComponent(BtnGerenciar)
                            .addComponent(btnSair))))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            String nomeProduto = comboBoxProdutos.getSelectedItem().toString();
            String data = TxtDataMovimentacao.getText();
            String qntdMovimentada = TxtQntdMovimentada.getText();
            String tipoMovimentacao = comboBoxTipodeMovimentacao.getSelectedItem().toString();

            if (nomeProduto.isEmpty() || data.isEmpty() || qntdMovimentada.isEmpty() || tipoMovimentacao.isEmpty()) {
                throw new Mensagem("Todos os campos devem ser preenchidos.");
            }

            if (!qntdMovimentada.matches("\\d+")) {
                throw new Mensagem("A quantidade deve conter apenas números.");
            }

            int quantidade = Integer.parseInt(qntdMovimentada);

            boolean cadastrou = objMovimentacao.insertMovimentacao(
                    nomeProduto,
                    data,
                    quantidade,
                    tipoMovimentacao
            );

            if (cadastrou) {
                JOptionPane.showMessageDialog(null, "Movimentação cadastrada com sucesso!");

                String alerta = objMovimentacao.getUltimoAlertaEstoque();

                if ("ABAIXO_MINIMO".equals(alerta)) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Atenção: o estoque do produto ficou ABAIXO do mínimo!",
                            "Alerta de Estoque",
                            JOptionPane.WARNING_MESSAGE
                    );
                } else if ("ACIMA_MAXIMO".equals(alerta)) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Atenção: o estoque do produto ficou ACIMA do máximo!",
                            "Alerta de Estoque",
                            JOptionPane.WARNING_MESSAGE
                    );
                }

                limparCampos();

            } else {
                // Cadastro bloqueado — verifica o motivo
                String alerta = objMovimentacao.getUltimoAlertaEstoque();

                if ("ESTOQUE_NEGATIVO".equals(alerta)) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Operação cancelada: a quantidade de saída é maior do que o estoque disponível!",
                            "Estoque Insuficiente",
                            JOptionPane.ERROR_MESSAGE
                    );
                } else {
                    JOptionPane.showMessageDialog(
                            null,
                            "Erro ao cadastrar movimentação.",
                            "Erro",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }

        } catch (Mensagem e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void BtnGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGerenciarActionPerformed
        TelaGerenciaMovimentacao tela = new TelaGerenciaMovimentacao();
        desktopPane.add(tela);

        tela.setVisible(true);
    }//GEN-LAST:event_BtnGerenciarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGerenciar;
    private javax.swing.JTextField TxtDataMovimentacao;
    private javax.swing.JTextField TxtQntdMovimentada;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> comboBoxProdutos;
    private javax.swing.JComboBox<String> comboBoxTipodeMovimentacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        TxtDataMovimentacao.setText("");
        TxtQntdMovimentada.setText("");
    }

    private void carregarProdutos() {

        comboBoxProdutos.removeAllItems();

        for (String produto : objProduto.listarNomesProdutos()) {

            comboBoxProdutos.addItem(produto);

        }
    }

}
