/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import bo.CategoriaBO;
import bo.ProdutoBO;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Categoria;

/**
 *
 * @author Weslen
 */
public class TelaProduto extends javax.swing.JInternalFrame {

    private ProdutoBO objetoProdutoBO = new ProdutoBO();
    private JDesktopPane desktopPane;
    private CategoriaBO objCategoria = new CategoriaBO();
    

    public TelaProduto(JDesktopPane desktopPane) {
        initComponents();

        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        setBorder(null);
        this.desktopPane = desktopPane;
        this.carregarCategorias();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrar = new javax.swing.JButton();
        BtnGerenciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        TxtNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtPreco = new javax.swing.JTextField();
        TxtQntdMaxima = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtQntdEstoque = new javax.swing.JTextField();
        TxtQntdMinima = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtUnidade = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        BtnGerenciar.setText("Gerenciar");
        BtnGerenciar.addActionListener(this::BtnGerenciarActionPerformed);

        jLabel2.setText("Nome do Produto: ");

        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);

        jLabel3.setText("Categoria");

        jLabel4.setText("Preço: ");

        TxtQntdMaxima.addActionListener(this::TxtQntdMaximaActionPerformed);

        jLabel5.setText("Quantidade em estoque:");

        jLabel7.setText("Quantidade máxima:");

        TxtQntdMinima.addActionListener(this::TxtQntdMinimaActionPerformed);

        jLabel8.setText("Quantidade minima:");

        jLabel9.setText("Unidade:");

        TxtUnidade.addActionListener(this::TxtUnidadeActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TxtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(TxtQntdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(TxtQntdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtQntdMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(TxtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnGerenciar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSair)
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtPreco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtQntdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtQntdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtQntdMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadastrar)
                            .addComponent(BtnGerenciar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            String nomeProduto = TxtNomeProduto.getText();
            Categoria categoriaSelecionada = (Categoria) jComboBoxCategoria.getSelectedItem();
            String preco = TxtPreco.getText();
            String quantidadeEstoque = TxtQntdEstoque.getText();
            String quantidadeMinima = TxtQntdMinima.getText();
            String quantidadeMaxima = TxtQntdMaxima.getText();
            String unidade = TxtUnidade.getText();

            if (nomeProduto.matches(".*\\d.*")) {
                throw new Mensagem("O nome do produto não pode conter números.");
            } else if (unidade.matches(".*\\d.*")) {
                throw new Mensagem("A unidade não pode conter números.");
            }

            if (!preco.matches("\\d+")) {
                throw new Mensagem("A quantidade deve conter apenas números.");

            } else if (!quantidadeEstoque.matches("\\d+")) {
                throw new Mensagem("A quantidade deve conter apenas números.");

            } else if (!quantidadeMinima.matches("\\d+")) {
                throw new Mensagem("A quantidade minima deve conter apenas números.");

            } else if (!quantidadeMaxima.matches("\\d+")) {
                throw new Mensagem("A quantidade maxima deve conter apenas números.");

            }

            int preco_produto = Integer.parseInt(preco);
            int qntdEstoque = Integer.parseInt(quantidadeEstoque);
            int qntdMin = Integer.parseInt(quantidadeMinima);
            int qntdMax = Integer.parseInt(quantidadeMaxima);

            if (nomeProduto.isEmpty() || preco.isEmpty() || quantidadeEstoque.isEmpty() || quantidadeMinima.isEmpty()
                    || quantidadeMaxima.isEmpty() || unidade.isEmpty()) {
                throw new Mensagem("Todos os campos devem ser preenchidos.");
            }

            //     boolean cadastrou = objMovimentacao.insertMovimentacao(
            //           nomeProduto,
            //         datx,
            //       quantidade,
            //     tipoMovimentacao
            // );
        } catch (Mensagem e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void BtnGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGerenciarActionPerformed
        TelaGerenciamentoProduto tela = new TelaGerenciamentoProduto();
        desktopPane.add(tela);

        tela.setVisible(true);
    }//GEN-LAST:event_BtnGerenciarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void TxtQntdMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtQntdMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtQntdMaximaActionPerformed

    private void TxtQntdMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtQntdMinimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtQntdMinimaActionPerformed

    private void TxtUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUnidadeActionPerformed

    
        private void carregarCategorias() {

        jComboBoxCategoria.removeAllItems();

        for (Categoria categoria : objCategoria.listarTodos()) {

            jComboBoxCategoria.addItem(categoria);

        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGerenciar;
    private javax.swing.JTextField TxtNomeProduto;
    private javax.swing.JTextField TxtPreco;
    private javax.swing.JTextField TxtQntdEstoque;
    private javax.swing.JTextField TxtQntdMaxima;
    private javax.swing.JTextField TxtQntdMinima;
    private javax.swing.JTextField TxtUnidade;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<Categoria> jComboBoxCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
