/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import bo.ProdutoBO;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName());

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();

        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuTelas = new javax.swing.JMenu();
        MenuItemCategoria = new javax.swing.JMenuItem();
        MenuItemProduto = new javax.swing.JMenuItem();
        MenuItemMovimentacao = new javax.swing.JMenuItem();
        JMenuReajusteDePreco = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        Fechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seja Bem-Vindo !");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Controle de Estoque");

        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel2)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        MenuTelas.setText("Telas");

        MenuItemCategoria.setText("Categoria");
        MenuItemCategoria.addActionListener(this::MenuItemCategoriaActionPerformed);
        MenuTelas.add(MenuItemCategoria);

        MenuItemProduto.setText("Produto");
        MenuTelas.add(MenuItemProduto);

        MenuItemMovimentacao.setText("Movimentação");
        MenuItemMovimentacao.addActionListener(this::MenuItemMovimentacaoActionPerformed);
        MenuTelas.add(MenuItemMovimentacao);

        JMenuReajusteDePreco.setText("Reajuste de preço");
        JMenuReajusteDePreco.addActionListener(this::JMenuReajusteDePrecoActionPerformed);
        MenuTelas.add(JMenuReajusteDePreco);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Relatorios");
        jCheckBoxMenuItem1.addActionListener(this::jCheckBoxMenuItem1ActionPerformed);
        MenuTelas.add(jCheckBoxMenuItem1);

        jMenuBar1.add(MenuTelas);

        Fechar.setText("Fechar");
        Fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FecharMouseClicked(evt);
            }
        });
        jMenuBar1.add(Fechar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_FecharMouseClicked

    private void MenuItemMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemMovimentacaoActionPerformed
        TelaMovimentacao tela = new TelaMovimentacao(desktopPane);

        desktopPane.add(tela);

        tela.setVisible(true);
    }//GEN-LAST:event_MenuItemMovimentacaoActionPerformed

    private void MenuItemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCategoriaActionPerformed
        TelaCategoria tela = new TelaCategoria(desktopPane);
        desktopPane.add(tela);

        tela.setVisible(true);
    }//GEN-LAST:event_MenuItemCategoriaActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        TelaRelatorios tela = new TelaRelatorios(desktopPane);
        desktopPane.add(tela);

        tela.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void JMenuReajusteDePrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuReajusteDePrecoActionPerformed
        String[] opcoes = {"Todos os Produtos", "Produto Específico"};

        int escolha = JOptionPane.showOptionDialog(
                null,
                "Deseja reajustar o preço de qual produto?",
                "Reajuste de Preço",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]
        );

        if (escolha == 0) {
            // Todos os produtos
            String input = JOptionPane.showInputDialog(
                    null,
                    "Digite a porcentagem de reajuste (ex: 10 para +10%, -5 para -5%):",
                    "Reajuste Geral",
                    JOptionPane.PLAIN_MESSAGE
            );

            if (input != null && !input.trim().isEmpty()) {
                try {
                    double porcentagem = Double.parseDouble(input.replace(",", "."));
                    ProdutoBO produtoBO = new ProdutoBO();
                    boolean ok = produtoBO.reajustarPrecoTodos(porcentagem);

                    if (ok) {
                        JOptionPane.showMessageDialog(null, "Preços reajustados com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ao reajustar preços.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Porcentagem inválida.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else if (escolha == 1) {
            // Produto específico — abre o InternalFrame
            TelaReajustePreco tela = new TelaReajustePreco(desktopPane);
            desktopPane.add(tela);
            tela.setVisible(true);
        }    }//GEN-LAST:event_JMenuReajusteDePrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Fechar;
    private javax.swing.JMenuItem JMenuReajusteDePreco;
    private javax.swing.JMenuItem MenuItemCategoria;
    private javax.swing.JMenuItem MenuItemMovimentacao;
    private javax.swing.JMenuItem MenuItemProduto;
    private javax.swing.JMenu MenuTelas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
