/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import bo.CategoriaBO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Categoria;

/**
 *
 * @author Home Office
 */
public class TelaGerenciaCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaGerenciaCategoria
     */
    private CategoriaBO objetoCategoria = new CategoriaBO();

    public TelaGerenciaCategoria() {
        initComponents();
        
                ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        setBorder(null);
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxEmbalagem = new javax.swing.JComboBox<>();
        BtnAlterar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnVoltar = new javax.swing.JButton();
        TxtNomeCategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxTamanho = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCategoria = new javax.swing.JTable();

        comboBoxEmbalagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lata", "Vidro", "Plástico" }));

        BtnAlterar.setText("Alterar");
        BtnAlterar.addActionListener(this::BtnAlterarActionPerformed);

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(this::BtnExcluirActionPerformed);

        jLabel2.setText("Nome da Categoria:");

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(this::BtnVoltarActionPerformed);

        jLabel3.setText("Tamanho:");

        jLabel4.setText("Embalagem:");

        comboBoxTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno", "Médio", "Grande" }));
        comboBoxTamanho.addActionListener(this::comboBoxTamanhoActionPerformed);

        jTableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Categoria", "Tamanho", "Embalagem"
            }
        ));
        jScrollPane1.setViewportView(jTableCategoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(BtnVoltar))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(TxtNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboBoxEmbalagem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxTamanho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnVoltar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        try {
            int linha = jTableCategoria.getSelectedRow();

            if (linha == -1) {
                throw new Mensagem(
                        "Selecione um aluno para alterar."
                );
            }
            String nomeCategoria = TxtNomeCategoria.getText();
            String embalagem = comboBoxEmbalagem.getSelectedItem().toString();
            String tamanho = comboBoxTamanho.getSelectedItem().toString();

            if (nomeCategoria.matches(".*\\d.*")) {
                throw new Mensagem("O nome do produto não pode conter números.");
            }

            int id = Integer.parseInt(
                    jTableCategoria.getValueAt(linha, 0).toString()
            );

            boolean alterou = objetoCategoria.atualizarCategoria(id, nomeCategoria, embalagem, tamanho);

            if (alterou) {

                JOptionPane.showMessageDialog(
                        rootPane,
                        "Categoria alterada com sucesso!"
                );

                carregaTabela();
                limparCampos();

            }

        } catch (Mensagem e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }


    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
       try {
            int linha = jTableCategoria.getSelectedRow();

            if (linha == -1) {
                BtnExcluir.setEnabled(false);
            } else {
                int id = Integer.parseInt(jTableCategoria.getValueAt(linha, 0).toString());
                int repostaUsuario = JOptionPane.showConfirmDialog(
                        null,
                        "Tem certeza que deseja apagar essa movimentação??"
                );
                if (repostaUsuario == JOptionPane.YES_OPTION) {
                    boolean apagou = objetoCategoria.deleteCategoria(id);

                    if (apagou) {
                        JOptionPane.showMessageDialog(
                                rootPane,
                                "Categoria apagado com sucesso!"
                        );

                        limparCampos();
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } finally {

            carregaTabela();
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void comboBoxTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTamanhoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JTextField TxtNomeCategoria;
    private javax.swing.JComboBox<String> comboBoxEmbalagem;
    private javax.swing.JComboBox<String> comboBoxTamanho;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCategoria;
    // End of variables declaration//GEN-END:variables

    private void carregaTabela() {
            DefaultTableModel modelo = (DefaultTableModel) this.jTableCategoria.getModel();
        modelo.setNumRows(0);

        ArrayList<Categoria> minhaLista = objetoCategoria.listarTodos();
            System.out.println(minhaLista.size());

        
        for (Categoria c : minhaLista) {
            modelo.addRow(new Object[]{
                c.getId_categoria(),
                c.getNome(),
                c.getTamanho(),
                c.getEmbalegem()
            });
        }
    }

    private void limparCampos() {
        TxtNomeCategoria.setText("");
        
    }

}
