/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import bo.MovimentacaoBO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Movimentacao;

public class TelaGerenciaMovimentacao extends javax.swing.JInternalFrame {

    private MovimentacaoBO objMovimentacao = new MovimentacaoBO();

    public TelaGerenciaMovimentacao() {
        initComponents();

        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        setBorder(null);
        this.carregaTabela();
        TxtNomeProduto.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMovimentacao = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        TxtNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtDataMovimentacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtQntdMovimentada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboBoxTipodeMovimentacao = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(879, 571));

        jTableMovimentacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Movimentação", "Produto", "Data Movimentação", "Quantidade Movimentada", "Tipo"
            }
        ));
        jTableMovimentacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMovimentacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMovimentacao);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        jLabel2.setText("Nome do Produto: ");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        jLabel3.setText("Data:");

        jLabel4.setText("Quantidade Movimentada: ");

        jLabel6.setText("Tipo da Movimentação:");

        comboBoxTipodeMovimentacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Saida" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar))
                    .addComponent(jLabel4)
                    .addComponent(TxtQntdMovimentada, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxTipodeMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TxtDataMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtNomeProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDataMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtQntdMovimentada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxTipodeMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnVoltar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            int linha = jTableMovimentacao.getSelectedRow();

            if (linha == -1) {
                btnExcluir.setEnabled(false);
            } else {
                int id = Integer.parseInt(jTableMovimentacao.getValueAt(linha, 0).toString());
                int repostaUsuario = JOptionPane.showConfirmDialog(
                        null,
                        "Tem certeza que deseja apagar essa movimentação??"
                );
                if (repostaUsuario == JOptionPane.YES_OPTION) {
                    boolean apagou = objMovimentacao.deleteMovimentacaoBO(id);

                    if (apagou) {
                        JOptionPane.showMessageDialog(
                                rootPane,
                                "Aluno apagado com sucesso!"
                        );

                        limparCampos();
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } finally {

            carregaTabela();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            int linha = jTableMovimentacao.getSelectedRow();

            if (linha == -1) {
                throw new Mensagem(
                        "Selecione um aluno para alterar."
                );
            }
            String nomeProduto = TxtNomeProduto.getText();
            String data = TxtDataMovimentacao.getText();
            String qntdMovimentada = TxtQntdMovimentada.getText();
            String tipoMovimentacao = comboBoxTipodeMovimentacao.getSelectedItem().toString();

            if (nomeProduto.matches(".*\\d.*")) {
                throw new Mensagem("O nome do produto não pode conter números.");
            }

            if (data.isEmpty()) {
                throw new Mensagem("Informe uma data.");
            }

            if (!qntdMovimentada.matches("\\d+")) {
                throw new Mensagem("A quantidade deve conter apenas números.");
            }

            int id = Integer.parseInt(
                    jTableMovimentacao.getValueAt(linha, 0).toString()
            );
            
            int quantidade = Integer.parseInt(qntdMovimentada);

            boolean alterou = objMovimentacao.atualizarMovimentacao(id,nomeProduto, data, quantidade, tipoMovimentacao);

            if (alterou) {

            JOptionPane.showMessageDialog(
                rootPane,
                "Movimentação alterada com sucesso!"
            );

            carregaTabela();
            limparCampos();
        }
            
        } catch (Mensagem e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jTableMovimentacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMovimentacaoMouseClicked
        if (this.jTableMovimentacao.getSelectedRow() != -1) {
            String nome_produto = this.jTableMovimentacao.getValueAt(this.jTableMovimentacao.getSelectedRow(), 1).toString();
            String data = this.jTableMovimentacao.getValueAt(this.jTableMovimentacao.getSelectedRow(), 2).toString();
            String qntd = this.jTableMovimentacao.getValueAt(this.jTableMovimentacao.getSelectedRow(), 3).toString();
            String tipo = this.jTableMovimentacao.getValueAt(this.jTableMovimentacao.getSelectedRow(), 4).toString();
            this.TxtNomeProduto.setText(nome_produto);
            this.TxtDataMovimentacao.setText(data);
            this.TxtQntdMovimentada.setText(qntd);
            this.comboBoxTipodeMovimentacao.setSelectedItem(tipo);
        }
    }//GEN-LAST:event_jTableMovimentacaoMouseClicked

    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTableMovimentacao.getModel();
        modelo.setNumRows(0);

        ArrayList<Movimentacao> minhaLista = objMovimentacao.listarTodos();
        for (Movimentacao m : minhaLista) {
            modelo.addRow(new Object[]{
                m.getId(),
                m.getNomeProduto(),
                m.getDataMovimentacao(),
                m.getQntdMovimentada(),
                m.getTipoMovimentacao()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDataMovimentacao;
    private javax.swing.JTextField TxtNomeProduto;
    private javax.swing.JTextField TxtQntdMovimentada;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboBoxTipodeMovimentacao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMovimentacao;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        TxtDataMovimentacao.setText("");
        TxtNomeProduto.setText("");
        TxtQntdMovimentada.setText("");
    }
}
